model_params:     # (channel, repeats)
  conv_channels : [[32, 1],
                   [64, 1],
                   [128, 1],
                   [256, 1],
                   [512, 1]]
  latent_dim : 128
  dropout : 0

data_params:
  train_data_dir : 'data/train_dataset'
  val_data_dir: 'data/val_dataset'
  img_size : 64
  batch_size : 64

training_params:
  learning_rate : 0.001
  w_kld : 1.e-2

trainer_params:
  max_epochs: 15000
  ckpt: ~ #'outputs/last.ckpt'
  check_val_every_n_epoch: 3

logging_params:
  log_dir: "tb_logs"